### ISSUE TITLE
What does this tool do?

### ISSUE THREAD

**Issue by gusow** [xcq1/timeguessr-plus#1]
Hi, creator of timeguessr here, just looking through some repos with the word timeguessr and I was wondering what does this do?

**Comment by xcq1** [comment]
@gusow Apologies for the late reply. This is a Tampermonkey script I made a while back when I was playing daily to add some simple features me and my friends were missing back then:

- Timers how long each round took you on daily and new game
- Extended breakdown popup showing all 5 images again with their description after completing a game
- An "exact share" option that just shared the numerical scores and timings (including score/timing per round)
- A "fuzzy share" option that also shared score/timing per round, but tried to only give a very vague idea about how well each round was played by randomizing score and time ranges and summarizing each in an emoji

I tried not to interfere with any important aspects of the site, but I haven't played in a while and the script seems to be broken now. Feel free to use anything, if you deem it useful. I may try to repair the script sometime, but I can also remove the repo if it bothers you.

**Comment by gusow** [comment]
No it doesn't bother me, no need to take it down.

That's neat, they're basically all features I intend on implementing within the game at some point... when I have some time to actually develop!

Thanks,
Gus

**Comment by xcq1** [comment]
Wonderful, thank you for the great game! I just checked today's daily, and I simply hadn't enabled "Dev Mode" for the Tampermonkey extension, the script still seems to work. :)
I'll close this issue, but feel free to reach out if there's anything else.
